name: flutter_movie_deep_dive_test
description: A movie flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  http: ^0.13.5
  bloc_test: ^9.1.1
  flutter_bloc: ^8.1.2
  network_image_mock: ^2.1.1

  
flutter:
  uses-material-design: true  
  assets:
   - assets/devfest.jpeg